language: node_js
branches:
  only:
    - master
    - 7.0.x
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - '12.4.0'
before_script:
  - npm install
  - npm prune
script:
  - npm run build:lib:prod
after_success:
  - npm run semantic-release
